# Generated by Django 4.0.6 on 2022-07-15 08:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0014_course_adviser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course_Adviser',
            new_name='CourseAdviser',
        ),
    ]
