# Generated by Django 4.0.6 on 2022-09-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_rename_course_adviser_courseadviser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'Session', 'verbose_name_plural': 'Session'},
        ),
        migrations.AlterField(
            model_name='courseadviser',
            name='staff_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='reg_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
